### ISSUE TITLE
Bug反馈

### ISSUE THREAD

**Issue by dhy2000** [Eadral/mars_buaa#1]
在无流水线延迟槽的设置下运行如下的汇编程序，当执行到第 12 行 `beq $t3 $t4 b2` （机器码为 `116c0002` ，PC 地址为 `00003020` ）的分支指令时，由于 `$t3` 和 `$t4` 不相等因此应顺序执行下一行的 `b1: sw $t3 8` ，此指令可产生一个写入 DM 的行为，但在此版本的 Mars 中，执行完 `beq` 之后直接执行了 `j end1` ，紧邻 `beq` 的 `sw` 指令被跳过了，导致该 Mars 的输出结果不正确。

发生该 bug 的汇编程序如下：
[test1.asm.txt](https://github.com/Eadral/mars_buaa/files/5548534/test1.asm.txt)

**Comment by Eadral** [comment]
这个版本不再维护无流水线延迟槽的设置了。
这个bug可能是在修复原版Mars的一个bug时引入的，原版Mars在延迟槽中指令发生异常时会有错误的行为。
